name: Build-VyOS-Sagitta-LTS-STABLE
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (Clean Start)
        uses: actions/checkout@v4
        with:
          repository: vyos/vyos-build # Budujemy z OFICJALNEGO repo, nie z Twojego forka!
          ref: sagitta
          fetch-depth: 0

      - name: Build ISO (The PRO Way)
        run: |
          # Czyścimy środowisko przed startem
          sudo rm -rf config/ .build/ build/
          
          # Uruchamiamy oficjalny kontener budujący
          docker run --rm --privileged -v $(pwd):/vyos -w /vyos vyos/vyos-build:sagitta \
          sudo ./build-vyos-image iso --architecture amd64 --build-by "123power-PRO" --build-type release

      - name: Upload Finished ISO
        uses: actions/upload-artifact@v4
        with:
          name: VyOS-1.4-Sagitta-LTS
          path: build/*.iso
